# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    pma_planar_2dof_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pma_planar_2dof_arm_controller:
  ros__parameters:
    joints:
      - pma_planar_2dof_shoulder
      - pma_planar_2dof_elbow
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity